In [1]:
import pandas as pd

df = pd.read_csv('../data/data.csv')
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,Unnamed: 60
0,Arab World,ARB,% of females ages 15-49 having comprehensive c...,SH.HIV.KNOW.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,% of males ages 15-49 having comprehensive cor...,SH.HIV.KNOW.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,133.555013,134.159119,134.857912,134.504576,134.105211,133.569626,...,49.999851,49.887046,49.781207,49.672975,49.536047,49.383745,48.796558,48.196418,NaN,NaN
3,Arab World,ARB,Adults (ages 15+) and children (0-14 years) li...,SH.HIV.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,Adults (ages 15+) and children (ages 0-14) new...,SH.HIV.INCD.TL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89005,Zimbabwe,ZWE,Use of insecticide-treated bed nets (% of unde...,SH.MLR.NETS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,17.300000,NaN,9.700000,NaN,NaN,26.800000,NaN,NaN
89006,Zimbabwe,ZWE,Use of Intermittent Preventive Treatment of ma...,SH.MLR.SPF2.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13.900000,NaN,7.300000,NaN,NaN,12.900000,NaN,NaN
89007,Zimbabwe,ZWE,Vitamin A supplementation coverage rate (% of ...,SN.ITK.VITA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,83.000000,0.000000,77.000000,49.000000,47.000000,61.000000,34.000000,32.000000,NaN,NaN
89008,Zimbabwe,ZWE,Wanted fertility rate (births per woman),SP.DYN.WFRT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.500000,NaN,NaN,NaN,NaN,NaN
89009,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,58.586086,58.760796,58.812421,58.825943,58.899308,58.939080,58.900126,58.822335,58.855551,NaN

In [78]:
# grab just the US in a dataframe
df_US = df[df['Country Name'] == 'United States'].transpose()
df_US.columns = df_US.iloc[3]
df_US.drop(df_US.index[3])
df_US

Indicator Code,SH.HIV.KNOW.FE.ZS,SH.HIV.KNOW.MA.ZS,SP.ADO.TFRT,SH.HIV.TOTL,SH.HIV.INCD.TL,SH.DYN.AIDS,SH.HIV.INCD,SP.DYN.SMAM.FE,SP.DYN.SMAM.MA,SP.POP.DPND,...,SP.URB.TOTL,SP.URB.TOTL.IN.ZS,SP.URB.GROW,SI.POV.URHC,SH.MLR.PREG.ZS,SH.MLR.NETS.ZS,SH.MLR.SPF2.ZS,SN.ITK.VITA.ZS,SP.DYN.WFRT,SH.DYN.AIDS.FE.ZS
Country Name,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States,...,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States
Country Code,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,...,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA
Indicator Name,% of females ages 15-49 having comprehensive c...,% of males ages 15-49 having comprehensive cor...,"Adolescent fertility rate (births per 1,000 wo...",Adults (ages 15+) and children (0-14 years) li...,Adults (ages 15+) and children (ages 0-14) new...,Adults (ages 15+) living with HIV,Adults (ages 15+) newly infected with HIV,"Age at first marriage, female","Age at first marriage, male",Age dependency ratio (% of working-age populat...,...,Urban population,Urban population (% of total),Urban population growth (annual %),Urban poverty headcount ratio at national pove...,Use of any antimalarial drug (% of pregnant wo...,Use of insecticide-treated bed nets (% of unde...,Use of Intermittent Preventive Treatment of ma...,Vitamin A supplementation coverage rate (% of ...,Wanted fertility rate (births per woman),Women's share of population ages 15+ living wi...
Indicator Code,SH.HIV.KNOW.FE.ZS,SH.HIV.KNOW.MA.ZS,SP.ADO.TFRT,SH.HIV.TOTL,SH.HIV.INCD.TL,SH.DYN.AIDS,SH.HIV.INCD,SP.DYN.SMAM.FE,SP.DYN.SMAM.MA,SP.POP.DPND,...,SP.URB.TOTL,SP.URB.TOTL.IN.ZS,SP.URB.GROW,SI.POV.URHC,SH.MLR.PREG.ZS,SH.MLR.NETS.ZS,SH.MLR.SPF2.ZS,SN.ITK.VITA.ZS,SP.DYN.WFRT,SH.DYN.AIDS.FE.ZS
1960,NaN,NaN,84.9872,NaN,NaN,NaN,NaN,NaN,NaN,66.5248,...,1.26462e+08,69.996,2.4491,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,NaN,NaN,30.023,NaN,NaN,NaN,NaN,NaN,NaN,49.2126,...,2.54762e+08,81.108,0.969153,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013,NaN,NaN,27.0666,NaN,NaN,NaN,NaN,NaN,NaN,49.6712,...,2.57183e+08,81.277,0.945553,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014,NaN,NaN,24.1102,NaN,NaN,NaN,NaN,NaN,NaN,50.2564,...,2.59741e+08,81.447,0.989639,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.9124,...,2.62332e+08,81.617,0.99293,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
# grab just the UK in a dataframe
df_UK = df[df['Country Name'] == 'United Kingdom'].transpose()
df_UK.columns = df_UK.iloc[3]
df_UK.drop(df_UK.index[3])
df_UK

Indicator Code,SH.HIV.KNOW.FE.ZS,SH.HIV.KNOW.MA.ZS,SP.ADO.TFRT,SH.HIV.TOTL,SH.HIV.INCD.TL,SH.DYN.AIDS,SH.HIV.INCD,SP.DYN.SMAM.FE,SP.DYN.SMAM.MA,SP.POP.DPND,...,SP.URB.TOTL,SP.URB.TOTL.IN.ZS,SP.URB.GROW,SI.POV.URHC,SH.MLR.PREG.ZS,SH.MLR.NETS.ZS,SH.MLR.SPF2.ZS,SN.ITK.VITA.ZS,SP.DYN.WFRT,SH.DYN.AIDS.FE.ZS
Country Name,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,...,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom,United Kingdom
Country Code,GBR,GBR,GBR,GBR,GBR,GBR,GBR,GBR,GBR,GBR,...,GBR,GBR,GBR,GBR,GBR,GBR,GBR,GBR,GBR,GBR
Indicator Name,% of females ages 15-49 having comprehensive c...,% of males ages 15-49 having comprehensive cor...,"Adolescent fertility rate (births per 1,000 wo...",Adults (ages 15+) and children (0-14 years) li...,Adults (ages 15+) and children (ages 0-14) new...,Adults (ages 15+) living with HIV,Adults (ages 15+) newly infected with HIV,"Age at first marriage, female","Age at first marriage, male",Age dependency ratio (% of working-age populat...,...,Urban population,Urban population (% of total),Urban population growth (annual %),Urban poverty headcount ratio at national pove...,Use of any antimalarial drug (% of pregnant wo...,Use of insecticide-treated bed nets (% of unde...,Use of Intermittent Preventive Treatment of ma...,Vitamin A supplementation coverage rate (% of ...,Wanted fertility rate (births per woman),Women's share of population ages 15+ living wi...
Indicator Code,SH.HIV.KNOW.FE.ZS,SH.HIV.KNOW.MA.ZS,SP.ADO.TFRT,SH.HIV.TOTL,SH.HIV.INCD.TL,SH.DYN.AIDS,SH.HIV.INCD,SP.DYN.SMAM.FE,SP.DYN.SMAM.MA,SP.POP.DPND,...,SP.URB.TOTL,SP.URB.TOTL.IN.ZS,SP.URB.GROW,SI.POV.URHC,SH.MLR.PREG.ZS,SH.MLR.NETS.ZS,SH.MLR.SPF2.ZS,SN.ITK.VITA.ZS,SP.DYN.WFRT,SH.DYN.AIDS.FE.ZS
1960,NaN,NaN,84.7406,NaN,NaN,NaN,NaN,NaN,NaN,53.6097,...,4.11047e+07,78.444,0.277314,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012,NaN,NaN,18.103,NaN,NaN,NaN,NaN,NaN,NaN,52.7465,...,5.21285e+07,81.834,1.01844,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013,NaN,NaN,16.7186,NaN,NaN,NaN,NaN,NaN,NaN,53.5198,...,5.26441e+07,82.092,0.984309,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014,NaN,NaN,15.3342,NaN,NaN,NaN,NaN,NaN,NaN,54.3232,...,5.32057e+07,82.345,1.06107,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.1219,...,5.3799e+07,82.592,1.10886,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
#getting just the two columns we want (for both data frames)
cols = ['SP.POP.TOTL', 'SP.DYN.CDRT.IN']

new_df_UK = pd.DataFrame(df_UK[cols])
new_df_US = pd.DataFrame(df_US[cols])

new_df_UK

Indicator Code        SP.POP.TOTL                        SP.DYN.CDRT.IN
Country Name       United Kingdom                        United Kingdom
Country Code                  GBR                                   GBR
Indicator Name  Population, total  Death rate, crude (per 1,000 people)
Indicator Code        SP.POP.TOTL                        SP.DYN.CDRT.IN
1960                     5.24e+07                                  11.5
...                           ...                                   ...
2012                  6.37003e+07                                   8.9
2013                  6.41282e+07                                     9
2014                  6.46132e+07                                   8.8
2015                  6.51382e+07                                   NaN
Unnamed: 60                   NaN                                   NaN

[61 rows x 2 columns]

In [81]:
new_df_US

Indicator Code        SP.POP.TOTL                        SP.DYN.CDRT.IN
Country Name        United States                         United States
Country Code                  USA                                   USA
Indicator Name  Population, total  Death rate, crude (per 1,000 people)
Indicator Code        SP.POP.TOTL                        SP.DYN.CDRT.IN
1960                  1.80671e+08                                   9.5
...                           ...                                   ...
2012                  3.14103e+08                                   8.1
2013                  3.16427e+08                                   8.1
2014                  3.18907e+08                                   8.1
2015                  3.21419e+08                                   NaN
Unnamed: 60                   NaN                                   NaN

[61 rows x 2 columns]

In [100]:
merged_df = new_df_US.join(new_df_UK, lsuffix='_US', rsuffix='_UK')

merged_df

Indicator Code,SP.POP.TOTL_US,SP.DYN.CDRT.IN_US,SP.POP.TOTL_UK,SP.DYN.CDRT.IN_UK
Country Name,United States,United States,United Kingdom,United Kingdom
Country Code,USA,USA,GBR,GBR
Indicator Name,"Population, total","Death rate, crude (per 1,000 people)","Population, total","Death rate, crude (per 1,000 people)"
Indicator Code,SP.POP.TOTL,SP.DYN.CDRT.IN,SP.POP.TOTL,SP.DYN.CDRT.IN
1960,1.80671e+08,9.5,5.24e+07,11.5
...,...,...,...,...
2012,3.14103e+08,8.1,6.37003e+07,8.9
2013,3.16427e+08,8.1,6.41282e+07,9
2014,3.18907e+08,8.1,6.46132e+07,8.8
2015,3.21419e+08,NaN,6.51382e+07,NaN
Unnamed: 60,NaN,NaN,NaN,NaN

In [101]:
merged_df.corr()

Empty DataFrame
Columns: []
Index: []

In [109]:
year_cols = [str(x) for x in list(range(1960, 2016))]
messing_around = pd.melt(df, 
                         id_vars=['Country Name','Country Code','Indicator Name','Indicator Code'], 
                         value_vars=year_cols)
messing_around.rename(columns = {'variable':'Year'}, inplace = True) 
messing_around.rename(columns = {'value':'Population'}, inplace = True) 
# messing_around.drop(['Indicator Code', 'Indicator Name'], axis=1, inplace=True)
# messing_around.sort_values(by=['Country Name', 'Year'])
# messing_around['Year'] = pd.to_numeric(messing_around['Year'])
# messing_around = messing_around[messing_around['Year']>=1985]

messing_around

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Population
0,Arab World,ARB,% of females ages 15-49 having comprehensive c...,SH.HIV.KNOW.FE.ZS,1960,NaN
1,Arab World,ARB,% of males ages 15-49 having comprehensive cor...,SH.HIV.KNOW.MA.ZS,1960,NaN
2,Arab World,ARB,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,1960,133.555013
3,Arab World,ARB,Adults (ages 15+) and children (0-14 years) li...,SH.HIV.TOTL,1960,NaN
4,Arab World,ARB,Adults (ages 15+) and children (ages 0-14) new...,SH.HIV.INCD.TL,1960,NaN
...,...,...,...,...,...,...
4984555,Zimbabwe,ZWE,Use of insecticide-treated bed nets (% of unde...,SH.MLR.NETS.ZS,2015,NaN
4984556,Zimbabwe,ZWE,Use of Intermittent Preventive Treatment of ma...,SH.MLR.SPF2.ZS,2015,NaN
4984557,Zimbabwe,ZWE,Vitamin A supplementation coverage rate (% of ...,SN.ITK.VITA.ZS,2015,NaN
4984558,Zimbabwe,ZWE,Wanted fertility rate (births per woman),SP.DYN.WFRT,2015,NaN
4984559,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,2015,58.855551