In [123]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [108]:
df = pd.read_csv('../data/data.csv')

In [109]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,Unnamed: 60
0,Arab World,ARB,% of females ages 15-49 having comprehensive c...,SH.HIV.KNOW.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,% of males ages 15-49 having comprehensive cor...,SH.HIV.KNOW.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,133.555013,134.159119,134.857912,134.504576,134.105211,133.569626,...,49.999851,49.887046,49.781207,49.672975,49.536047,49.383745,48.796558,48.196418,NaN,NaN
3,Arab World,ARB,Adults (ages 15+) and children (0-14 years) li...,SH.HIV.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,Adults (ages 15+) and children (ages 0-14) new...,SH.HIV.INCD.TL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89010 entries, 0 to 89009
Data columns (total 61 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    89010 non-null  object
 1   Country Code    89010 non-null  object
 2   Indicator Name  89010 non-null  object
 3   Indicator Code  89010 non-null  object
 4   1960            35482 non-null  float64
 5   1961            35325 non-null  float64
 6   1962            35889 non-null  float64
 7   1963            35452 non-null  float64
 8   1964            35483 non-null  float64
 9   1965            35603 non-null  float64
 10  1966            35538 non-null  float64
 11  1967            36022 non-null  float64
 12  1968            35577 non-null  float64
 13  1969            35630 non-null  float64
 14  1970            36910 non-null  float64
 15  1971            37578 non-null  float64
 16  1972            38015 non-null  float64
 17  1973            37542 non-null  float64
 18  1974            37574 non-null  float64
 19  1975            37760 non-null  float64
 20  1976            37778 non-null  float64
 21  1977            38204 non-null  float64
 22  1978            37797 non-null  float64
 23  1979            37848 non-null  float64
 24  1980            38578 non-null  float64
 25  1981            38829 non-null  float64
 26  1982            39182 non-null  float64
 27  1983            38772 non-null  float64
 28  1984            38964 non-null  float64
 29  1985            39020 non-null  float64
 30  1986            39367 non-null  float64
 31  1987            39832 non-null  float64
 32  1988            39166 non-null  float64
 33  1989            39282 non-null  float64
 34  1990            47722 non-null  float64
 35  1991            47231 non-null  float64
 36  1992            47923 non-null  float64
 37  1993            47398 non-null  float64
 38  1994            47678 non-null  float64
 39  1995            51326 non-null  float64
 40  1996            51386 non-null  float64
 41  1997            51560 non-null  float64
 42  1998            51404 non-null  float64
 43  1999            52442 non-null  float64
 44  2000            56672 non-null  float64
 45  2001            52924 non-null  float64
 46  2002            53536 non-null  float64
 47  2003            53013 non-null  float64
 48  2004            53417 non-null  float64
 49  2005            54304 non-null  float64
 50  2006            54398 non-null  float64
 51  2007            54255 non-null  float64
 52  2008            53878 non-null  float64
 53  2009            54437 non-null  float64
 54  2010            57099 non-null  float64
 55  2011            54922 non-null  float64
 56  2012            54927 non-null  float64
 57  2013            52924 non-null  float64
 58  2014            52199 non-null  float64
 59  2015            43068 non-null  float64
 60  Unnamed: 60     0 non-null      float64
dtypes: float64(57), object(4)
memory usage: 41.4+ MB

In [111]:
df.tail()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,Unnamed: 60
89005,Zimbabwe,ZWE,Use of insecticide-treated bed nets (% of unde...,SH.MLR.NETS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,17.300000,NaN,9.700000,NaN,NaN,26.800000,NaN,NaN
89006,Zimbabwe,ZWE,Use of Intermittent Preventive Treatment of ma...,SH.MLR.SPF2.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,13.900000,NaN,7.300000,NaN,NaN,12.900000,NaN,NaN
89007,Zimbabwe,ZWE,Vitamin A supplementation coverage rate (% of ...,SN.ITK.VITA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,83.000000,0.000000,77.000000,49.000000,47.000000,61.00000,34.000000,32.000000,NaN,NaN
89008,Zimbabwe,ZWE,Wanted fertility rate (births per woman),SP.DYN.WFRT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.500000,NaN,NaN,NaN,NaN,NaN
89009,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,58.586086,58.760796,58.812421,58.825943,58.899308,58.93908,58.900126,58.822335,58.855551,NaN

In [112]:
len(set(df.columns))

61

In [113]:
len(set(df.loc[:,'Country Name']))

258

In [114]:
df_US = df[df['Country Name'] == 'United States'] #make US only Dataframe
df_US = df_US.transpose()

df_US.columns = df_US.iloc[3] #make the colums the values for row 4 (indicator code) 
df_US.drop(df_US.index[3], inplace=True) #drop the indicator code row since its now the column name
df_sqeezed = df_US.squeeze('columns') #squeezes df on the columns to eliminate duplicate indicator codes
df_sqeezed

Indicator Code,SH.HIV.KNOW.FE.ZS,SH.HIV.KNOW.MA.ZS,SP.ADO.TFRT,SH.HIV.TOTL,SH.HIV.INCD.TL,SH.DYN.AIDS,SH.HIV.INCD,SP.DYN.SMAM.FE,SP.DYN.SMAM.MA,SP.POP.DPND,...,SP.URB.TOTL,SP.URB.TOTL.IN.ZS,SP.URB.GROW,SI.POV.URHC,SH.MLR.PREG.ZS,SH.MLR.NETS.ZS,SH.MLR.SPF2.ZS,SN.ITK.VITA.ZS,SP.DYN.WFRT,SH.DYN.AIDS.FE.ZS
Country Name,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States,...,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States
Country Code,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA,...,USA,USA,USA,USA,USA,USA,USA,USA,USA,USA
Indicator Name,% of females ages 15-49 having comprehensive c...,% of males ages 15-49 having comprehensive cor...,"Adolescent fertility rate (births per 1,000 wo...",Adults (ages 15+) and children (0-14 years) li...,Adults (ages 15+) and children (ages 0-14) new...,Adults (ages 15+) living with HIV,Adults (ages 15+) newly infected with HIV,"Age at first marriage, female","Age at first marriage, male",Age dependency ratio (% of working-age populat...,...,Urban population,Urban population (% of total),Urban population growth (annual %),Urban poverty headcount ratio at national pove...,Use of any antimalarial drug (% of pregnant wo...,Use of insecticide-treated bed nets (% of unde...,Use of Intermittent Preventive Treatment of ma...,Vitamin A supplementation coverage rate (% of ...,Wanted fertility rate (births per woman),Women's share of population ages 15+ living wi...
1960,NaN,NaN,84.9872,NaN,NaN,NaN,NaN,NaN,NaN,66.5248,...,1.26462e+08,69.996,2.4491,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961,NaN,NaN,82.7346,NaN,NaN,NaN,NaN,NaN,NaN,67.0617,...,1.29276e+08,70.377,2.20057,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962,NaN,NaN,80.482,NaN,NaN,NaN,NaN,NaN,NaN,67.1348,...,1.31989e+08,70.757,2.07649,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1963,NaN,NaN,77.9506,NaN,NaN,NaN,NaN,NaN,NaN,66.8483,...,1.34615e+08,71.134,1.97056,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964,NaN,NaN,75.4192,NaN,NaN,NaN,NaN,NaN,NaN,66.3405,...,1.37216e+08,71.508,1.91344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1965,NaN,NaN,72.8878,NaN,NaN,NaN,NaN,NaN,NaN,65.6766,...,1.39663e+08,71.879,1.76765,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1966,NaN,NaN,70.3564,NaN,NaN,NaN,NaN,NaN,NaN,64.9595,...,1.42009e+08,72.247,1.66556,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1967,NaN,NaN,67.825,NaN,NaN,NaN,NaN,NaN,NaN,64.1126,...,1.44289e+08,72.612,1.59282,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1968,NaN,NaN,66.466,NaN,NaN,NaN,NaN,NaN,NaN,63.1741,...,1.46463e+08,72.974,1.49576,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969,NaN,NaN,65.107,NaN,NaN,NaN,NaN,NaN,NaN,62.1765,...,1.48629e+08,73.333,1.46799,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970,NaN,NaN,63.748,NaN,NaN,NaN,NaN,21.5,23.5,61.1358,...,1.50922e+08,73.602,1.53115,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1971,NaN,NaN,62.389,NaN,NaN,NaN,NaN,NaN,NaN,59.8533,...,1.52865e+08,73.613,1.27928,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1972,NaN,NaN,61.03,NaN,NaN,NaN,NaN,NaN,NaN,58.6543,...,1.54532e+08,73.623,1.08411,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1973,NaN,NaN,59.3726,NaN,NaN,NaN,NaN,NaN,NaN,57.4945,...,1.56035e+08,73.633,0.968059,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1974,NaN,NaN,57.7152,NaN,NaN,NaN,NaN,NaN,NaN,56.3184,...,1.57489e+08,73.643,0.92724,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975,NaN,NaN,56.0578,NaN,NaN,NaN,NaN,NaN,NaN,55.114,...,1.59071e+08,73.653,0.999565,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1976,NaN,NaN,54.4004,NaN,NaN,NaN,NaN,NaN,NaN,54.4067,...,1.60611e+08,73.663,0.963796,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1977,NaN,NaN,52.743,NaN,NaN,NaN,NaN,NaN,NaN,53.6247,...,1.62257e+08,73.673,1.01935,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1978,NaN,NaN,52.5098,NaN,NaN,NaN,NaN,NaN,NaN,52.8506,...,1.64005e+08,73.682,1.07179,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1979,NaN,NaN,52.2766,NaN,NaN,NaN,NaN,NaN,NaN,52.1806,...,1.65848e+08,73.692,1.11715,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980,NaN,NaN,52.0434,NaN,NaN,NaN,NaN,23.3,25.2,51.6542,...,1.67551e+08,73.738,1.02199,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981,NaN,NaN,51.8102,NaN,NaN,NaN,NaN,NaN,NaN,51.2423,...,1.69552e+08,73.89,1.18734,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982,NaN,NaN,51.577,NaN,NaN,NaN,NaN,NaN,NaN,50.9307,...,1.71529e+08,74.042,1.15882,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983,NaN,NaN,51.9174,NaN,NaN,NaN,NaN,NaN,NaN,50.7365,...,1.7346e+08,74.194,1.11946,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1984,NaN,NaN,52.2578,NaN,NaN,NaN,NaN,NaN,NaN,50.6441,...,1.75322e+08,74.344,1.06779,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1985,NaN,NaN,52.5982,NaN,NaN,NaN,NaN,NaN,NaN,50.6306,...,1.77239e+08,74.494,1.08769,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986,NaN,NaN,52.9386,NaN,NaN,NaN,NaN,NaN,NaN,50.8755,...,1.79245e+08,74.644,1.12532,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987,NaN,NaN,53.279,NaN,NaN,NaN,NaN,NaN,NaN,51.127,...,1.81215e+08,74.793,1.09324,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988,NaN,NaN,54.5456,NaN,NaN,NaN,NaN,NaN,NaN,51.3758,...,1.83232e+08,74.942,1.10702,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1989,NaN,NaN,55.8122,NaN,NaN,NaN,NaN,NaN,NaN,51.6045,...,1.85334e+08,75.089,1.14036,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990,NaN,NaN,57.0788,NaN,NaN,NaN,NaN,25.4,27.6,51.7947,...,1.87966e+08,75.3,1.41026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991,NaN,NaN,58.3454,NaN,NaN,NaN,NaN,NaN,NaN,52.1157,...,1.91509e+08,75.701,1.86738,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992,NaN,NaN,59.612,NaN,NaN,NaN,NaN,NaN,NaN,52.3682,...,1.95199e+08,76.097,1.90863,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993,NaN,NaN,57.9556,NaN,NaN,NaN,NaN,NaN,NaN,52.5072,...,1.98807e+08,76.488,1.83118,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994,NaN,NaN,56.2992,NaN,NaN,NaN,NaN,NaN,NaN,52.4868,...,2.02278e+08,76.875,1.73098,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995,NaN,NaN,54.6428,NaN,NaN,NaN,NaN,23.3,NaN,52.3008,...,2.05718e+08,77.257,1.68647,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,NaN,NaN,52.9864,NaN,NaN,NaN,NaN,NaN,NaN,52.1789,...,2.09147e+08,77.636,1.65278,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,NaN,NaN,51.33,NaN,NaN,NaN,NaN,NaN,NaN,51.8606,...,2.12694e+08,78.008,1.68198,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,NaN,NaN,49.7042,NaN,NaN,NaN,NaN,NaN,NaN,51.4265,...,2.16206e+08,78.377,1.63763,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,NaN,NaN,48.0784,NaN,NaN,NaN,NaN,NaN,NaN,50.9757,...,2.19722e+08,78.742,1.61296,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000,NaN,NaN,46.4526,NaN,NaN,NaN,NaN,26,27.8,50.5497,...,2.23069e+08,79.057,1.51201,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001,NaN,NaN,44.8268,NaN,NaN,NaN,NaN,NaN,NaN,50.1058,...,2.25792e+08,79.234,1.21338,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002,NaN,NaN,43.201,NaN,NaN,NaN,NaN,23.7,24,49.7632,...,2.284e+08,79.409,1.14842,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003,NaN,NaN,42.4946,NaN,NaN,NaN,NaN,NaN,NaN,49.4577,...,2.30877e+08,79.583,1.07836,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004,NaN,NaN,41.7882,NaN,NaN,NaN,NaN,NaN,NaN,49.1077,...,2.33533e+08,79.757,1.14389,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005,NaN,NaN,41.0818,NaN,NaN,NaN,NaN,NaN,NaN,48.6968,...,2.36201e+08,79.928,1.13588,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006,NaN,NaN,40.3754,NaN,NaN,NaN,NaN,NaN,NaN,48.7172,...,2.38999e+08,80.099,1.17797,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007,NaN,NaN,39.669,NaN,NaN,NaN,NaN,23.7,NaN,48.649,...,2.41795e+08,80.269,1.16307,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008,NaN,NaN,37.7398,NaN,NaN,NaN,NaN,NaN,NaN,48.57,...,2.44607e+08,80.438,1.15619,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009,NaN,NaN,35.8106,NaN,NaN,NaN,NaN,26.9,28.8,48.5846,...,2.47276e+08,80.606,1.08529,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,NaN,NaN,33.8814,NaN,NaN,NaN,NaN,NaN,NaN,48.734,...,2.49866e+08,80.772,1.04172,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011,NaN,NaN,31.9522,NaN,NaN,NaN,NaN,NaN,NaN,48.9122,...,2.52305e+08,80.94,0.971627,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012,NaN,NaN,30.023,NaN,NaN,NaN,NaN,NaN,NaN,49.2126,...,2.54762e+08,81.108,0.969153,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013,NaN,NaN,27.0666,NaN,NaN,NaN,NaN,NaN,NaN,49.6712,...,2.57183e+08,81.277,0.945553,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014,NaN,NaN,24.1102,NaN,NaN,NaN,NaN,NaN,NaN,50.2564,...,2.59741e+08,81.447,0.989639,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.9124,...,2.62332e+08,81.617,0.99293,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [115]:
df_US_pretranspose = df.loc[df['Country Name']=='United States',:]
df_UK_pretranspose = df.loc[df['Country Name']=='United Kingdom',:]

In [116]:
df_US_ = df_US_pretranspose.transpose()

In [124]:
df_US_mort = df_US_.drop('Country Name').loc[:,(df['Indicator Code'] == 'SP.DYN.CDRT.IN') | (df['Indicator Code'] == 'SP.POP.TOTL')]
df_US_mort

                                               85306              85482
Country Code                                     USA                USA
Indicator Name  Death rate, crude (per 1,000 people)  Population, total
Indicator Code                        SP.DYN.CDRT.IN        SP.POP.TOTL
1960                                             9.5        1.80671e+08
1961                                             9.3        1.83691e+08
1962                                             9.5        1.86538e+08
1963                                             9.6        1.89242e+08
1964                                             9.4        1.91889e+08
1965                                             9.4        1.94303e+08
1966                                             9.5         1.9656e+08
1967                                             9.4        1.98712e+08
1968                                             9.8        2.00706e+08
1969                                             9.5        2.02677e+08
1970                                             9.5        2.05052e+08
1971                                             9.3        2.07661e+08
1972                                             9.4        2.09896e+08
1973                                             9.3        2.11909e+08
1974                                             9.1        2.13854e+08
1975                                             8.8        2.15973e+08
1976                                             8.8        2.18035e+08
1977                                             8.6        2.20239e+08
1978                                             8.7        2.22585e+08
1979                                             8.5        2.25055e+08
1980                                             8.8        2.27225e+08
1981                                             8.6        2.29466e+08
1982                                             8.5        2.31664e+08
1983                                             8.6        2.33792e+08
1984                                             8.7        2.35825e+08
1985                                             8.7        2.37924e+08
1986                                             8.7        2.40133e+08
1987                                             8.6        2.42289e+08
1988                                             8.9        2.44499e+08
1989                                             8.8        2.46819e+08
1990                                             8.6        2.49623e+08
1991                                             8.6        2.52981e+08
1992                                             8.5        2.56514e+08
1993                                             8.8        2.59919e+08
1994                                             8.8        2.63126e+08
1995                                             8.8        2.66278e+08
1996                                             8.8        2.69394e+08
1997                                             8.7        2.72657e+08
1998                                             8.6        2.75854e+08
1999                                             8.6         2.7904e+08
2000                                             8.5        2.82162e+08
2001                                             8.5        2.84969e+08
2002                                             8.5        2.87625e+08
2003                                             8.4        2.90108e+08
2004                                             8.2        2.92805e+08
2005                                             8.3        2.95517e+08
2006                                             8.1         2.9838e+08
2007                                               8        3.01231e+08
2008                                             8.1        3.04094e+08
2009                                             7.9        3.06772e+08
2010                                               8        3.09347e+08
2011                                             8.1        3.11719e+08
2012                                             8.1        3.14103e+08
2013                                             8.1        3.16427e+08
2014                                             8.1        3.18907e+08
2015                                             NaN        3.21419e+08
Unnamed: 60                                      NaN                NaN

In [118]:
df_UK_ = df_UK_pretranspose.transpose()

In [121]:
df_UK_mort = df_UK_.drop('Country Name').loc[:,(df['Indicator Code'] == 'SP.DYN.CDRT.IN') | (df['Indicator Code'] == 'SP.POP.TOTL')]
df_UK_mort

                                               84961              85137
Country Code                                     GBR                GBR
Indicator Name  Death rate, crude (per 1,000 people)  Population, total
Indicator Code                        SP.DYN.CDRT.IN        SP.POP.TOTL
1960                                            11.5           5.24e+07
1961                                              12           5.28e+07
1962                                            11.9          5.325e+07
1963                                            12.2          5.365e+07
1964                                            11.3            5.4e+07
1965                                            11.6        5.43480e+07
1966                                            11.8        5.46485e+07
1967                                            11.2        5.49436e+07
1968                                            11.9        5.52117e+07
1969                                            11.9        5.54418e+07
1970                                            11.8        5.56632e+07
1971                                            11.5        5.58962e+07
1972                                              12        5.60861e+07
1973                                            11.9        5.61945e+07
1974                                            11.9          5.623e+07
1975                                            11.8        5.62258e+07
1976                                            12.1         5.6212e+07
1977                                            11.7        5.61935e+07
1978                                            11.9        5.61965e+07
1979                                              12         5.6247e+07
1980                                            11.7        5.63142e+07
1981                                            11.7        5.63338e+07
1982                                            11.8        5.63136e+07
1983                                            11.7        5.63328e+07
1984                                            11.4        5.64221e+07
1985                                            11.9        5.65503e+07
1986                                            11.7        5.66814e+07
1987                                            11.3        5.68020e+07
1988                                            11.4        5.69283e+07
1989                                            11.5        5.70767e+07
1990                                            11.2        5.72476e+07
1991                                            11.3        5.74249e+07
1992                                              11        5.75804e+07
1993                                            11.4        5.77186e+07
1994                                            10.8        5.78657e+07
1995                                            11.1         5.8019e+07
1996                                            10.9         5.8167e+07
1997                                            10.8         5.8317e+07
1998                                            10.8        5.84871e+07
1999                                            10.8        5.86825e+07
2000                                            10.3        5.88925e+07
2001                                            10.2        5.91197e+07
2002                                            10.2        5.93705e+07
2003                                            10.2        5.96476e+07
2004                                             9.7        5.99879e+07
2005                                             9.6        6.04012e+07
2006                                             9.4        6.08468e+07
2007                                             9.4        6.13225e+07
2008                                             9.4         6.1807e+07
2009                                               9        6.22763e+07
2010                                             8.9        6.27664e+07
2011                                             8.7        6.32589e+07
2012                                             8.9        6.37003e+07
2013                                               9        6.41282e+07
2014                                             8.8        6.46132e+07
2015                                             NaN        6.51382e+07
Unnamed: 60                                      NaN                NaN

In [120]:
fig, ax = subplot(1,2)

AttributeError: module 'pandas' has no attribute 'mer'